### ISSUE TITLE
OOM with every model after recent ComfyUI update

### ISSUE THREAD

**Issue by caniyabanci76** [1038lab/ComfyUI-QwenVL#156]
I have 24GB VRAM, but after a recent update, I'm getting OOM errors regardless of which variant of Qwen3-VL I used, even with the `Qwen3-VL-2B-Instruct` model.  Crash is very instant and seems to happen prior to even loading the model. 

```
To see the GUI go to: http://0.0.0.0:8188
To see the GUI go to: http://[::]:8188
got prompt
[QwenVL] Node on nvidia_gpu
[QwenVL] BitsAndBytes quantization detected - forcing SDPA attention
[QwenVL] Attention backend selected: sdpa
[QwenVL] Loading Qwen3-VL-2B-Instruct (8-bit (Balanced), attn=sdpa)
Loading weights:   0%|                  | 1/625 [00:00<00:00, 4369.07it/s, Materializing param=model.language_model.embed_tokens.weight]
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "/home/jkk/ai/ComfyUI/execution.py", line 524, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkk/ai/ComfyUI/execution.py", line 333, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkk/ai/ComfyUI/execution.py", line 307, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/home/jkk/ai/ComfyUI/execution.py", line 295, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "/home/jkk/ai/ComfyUI/custom_nodes/ComfyUI-QwenVL/AILab_QwenVL.py", line 890, in process
    return self.run(model_name, quantization, preset_prompt, custom_prompt, image, video, 16, max_tokens, 0.6, 0.9, 1, 1.2, seed, keep_model_loaded, attention_mode, False, "auto")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkk/ai/ComfyUI/custom_nodes/ComfyUI-QwenVL/AILab_QwenVL.py", line 828, in run
    self.load_model(
  File "/home/jkk/ai/ComfyUI/custom_nodes/ComfyUI-QwenVL/AILab_QwenVL.py", line 730, in load_model
    self.model = AutoModelForVision2Seq.from_pretrained(model_path, **load_kwargs).eval()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkk/ai/ComfyUI/venv/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 374, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkk/ai/ComfyUI/venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 4072, in from_pretrained
    loading_info, disk_offload_index = cls._load_pretrained_model(model, state_dict, checkpoint_files, load_config)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkk/ai/ComfyUI/venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 4191, in _load_pretrained_model
    loading_info, disk_offload_index = convert_and_load_state_dict_in_model(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkk/ai/ComfyUI/venv/lib/python3.12/site-packages/transformers/core_model_loading.py", line 1209, in convert_and_load_state_dict_in_model
    realized_value = mapping.convert(
                     ^^^^^^^^^^^^^^^^
  File "/home/jkk/ai/ComfyUI/venv/lib/python3.12/site-packages/transformers/core_model_loading.py", line 677, in convert
    collected_tensors = self.materialize_tensors()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkk/ai/ComfyUI/venv/lib/python3.12/site-packages/transformers/core_model_loading.py", line 653, in materialize_tensors
    tensors = [future.result() for future in tensors if future.result() is not None]
                                                        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkk/ai/ComfyUI/venv/lib/python3.12/site-packages/transformers/core_model_loading.py", line 799, in _job
    return _materialize_copy(tensor, device, dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkk/ai/ComfyUI/venv/lib/python3.12/site-packages/transformers/core_model_loading.py", line 788, in _materialize_copy
    tensor = tensor.to(device=device, dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device

Memory summary: |===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |  28676 KiB |   2329 MiB |      0 B   |      0 B   |
|       from large pool |      0 KiB |      0 MiB |      0 B   |      0 B   |
|       from small pool |      0 KiB |      0 MiB |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Active memory         |  28676 KiB |   2329 MiB |      0 B   |      0 B   |
|       from large pool |      0 KiB |      0 MiB |      0 B   |      0 B   |
|       from small pool |      0 KiB |      0 MiB |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Requested memory      |      0 B   |      0 B   |      0 B   |      0 B   |
|       from large pool |      0 B   |      0 B   |      0 B   |      0 B   |
|       from small pool |      0 B   |      0 B   |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| GPU reserved memory   |   2336 MiB |   2336 MiB |      0 B   |      0 B   |
|       from large pool |      0 MiB |      0 MiB |      0 B   |      0 B   |
|       from small pool |      0 MiB |      0 MiB |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Non-releasable memory |      0 B   |      0 B   |      0 B   |      0 B   |
|       from large pool |      0 B   |      0 B   |      0 B   |      0 B   |
|       from small pool |      0 B   |      0 B   |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Allocations           |       0    |       0    |       0    |       0    |
|       from large pool |       0    |       0    |       0    |       0    |
|       from small pool |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Active allocs         |       0    |       0    |       0    |       0    |
|       from large pool |       0    |       0    |       0    |       0    |
|       from small pool |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| GPU reserved segments |       0    |       0    |       0    |       0    |
|       from large pool |       0    |       0    |       0    |       0    |
|       from small pool |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |       0    |       0    |       0    |       0    |
|       from large pool |       0    |       0    |       0    |       0    |
|       from small pool |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|

Got an OOM, unloading all loaded models.
```

**Comment by bondobrus** [comment]
Quick workaround is to set `--disable-dynamic-vram` as flag while running comfyui. Surely code needs to be updated. Dynamic vram is now enabled by default in comfy

**Comment by caniyabanci76** [comment]
> Quick workaround is to set `--disable-dynamic-vram` as flag while running comfyui. Surely code needs to be updated. Dynamic vram is now enabled by default in comfy

Thank you.  I hope they update the nodes so they don't fight against comfyui's new memory management system

**Comment by Khaarthur** [comment]
@bondobrus it's work! Thank you very much

**Comment by Chuckame** [comment]
Seems not fixed in the end, as dynamic vram improves many things... Isn't there another way to fix it ?

**Comment by caniyabanci76** [comment]
> Seems not fixed in the end, as dynamic vram improves many things... Isn't there another way to fix it ?

I got Claude Code to clone the node asking it to avoid the error (also simplified it a bit), and it worked.  I will not release it since I am not in a position to support it, sorry. But it's not a difficult fix

**Comment by Chuckame** [comment]
So you could publish it in a PR, and even close it just after, at least to share what has been done.

It could be reused by maintainers or another random contributor to merge it.
